/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is normally generated by Next.js on `next dev`/`next build`.
// It is checked in here only so `tsc --noEmit` type-checks cleanly before the
// first build. Do not edit it manually.
